# TODOs
- paperwork/group-reflection.md:
  - description: No TODO markers left in group-reflection.md
    category: Paperwork
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- description: No TODO markers left in any individual reflection
  category: Paperwork
  check: ExecuteCommand
  options:
    command: "cd paperwork && bash .todos"
- src/main.py:
  - description: No TODO markers left in the main.py file
    category: Control Room
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true